### PR TITLE
fix: support comma separated files input

### PR DESCRIPTION
**Pull request by p5**
You are not able to pass in multiple lines to GITHUB_ENV, so this changes the action to support comma-separated list of inputs instead.  

Added a `clean` step to the Containerfile to remove cache as this does not need to be distributed with the image.

Added a new spec file to the test workflow to validate if the changes in this PR work as expected.

### CODE REVIEW

**Review by EyeCantCU — APPROVED** [review]
Everything here looks great, really appreciate the pull request!

**Comment by p5** [comment]
> Everything here looks great, really appreciate the pull request!

Please note I have not tested anything in this PR.  May not be good to merge yet

**Comment by EyeCantCU** [comment]
> > Everything here looks great, really appreciate the pull request!
> 
> Please note I have not tested anything in this PR. May not be good to merge yet

Yup. I had figured as it is a draft. I can add a test real fast to ensure everything is good :)

**Comment by EyeCantCU** [comment]
@p5 looks like it works! Any additions you'd like to make to this pull request?

**Comment by p5** [comment]
> @p5 looks like it works! Any additions you'd like to make to this pull request?

Thanks for reviewing and testing!
Nothing I can think of.  It does everything we need it to, but can always add more later when we find it

I'm on mobile and can't find the button to mark it ready for review, so happy for you to merge when ready.

**Comment by EyeCantCU** [comment]
Terrific! Once again, thank you. Will merge now

**Pull request merged**
